defaults: &defaults
  host: 127.0.0.1
  port: 27017
  database: forgecraft

development:
  <<: *defaults
  database: forgecraft

test:
  <<: *defaults
  database: forgecraft_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: staff.mongohq.com
  port: 10064
  databse: app929333
  username: heroku
  password: 193170bs
