development:
  host: localhost
  database: forgecraft

test:
  host: localhost
  database: forgecraft_test

# set these environment variables on your prod server
production:
  host: staff.mongohq.com
  port: 10064
  database: app929333
  username: heroku
  password: 193170bs
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
